# Generated by Django 3.1.3 on 2020-11-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': 'Options', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'QuizQuestion', 'verbose_name_plural': 'QuizQuestion'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(max_length=255),
        ),
    ]
